language: EN
sast:
  include:
    - .
  exclude: # Optional: paths to exclude from scanning
    - node_modules
    - vendor
strict: true
strictness_threshold: low
output:
  file_path: results.csv
  format: CSV